apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-canary-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-canary
  template:
    metadata:
      labels:
        app: flask-canary
    spec:
      containers:
      - name: flask-container
        image: rajukolupula/python-repo:latest
        ports:
        - containerPort: 5000
